sudo: required
services:
  - docker

before_install:
  - docker build -t frayside10/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true frayside10/react-test npm test

after_success:
  - docker build -t frayside10/multi-client ./client
  - docker build -t frayside10/multi-nginx ./nginx
  - docker build -t frayside10/multi-server ./server
  - docker build -t frayside10/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push frayside10/multi-client
  - docker push frayside10/multi-nginx
  - docker push frayside10/multi-server
  - docker push frayside10/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-760706690850
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

